# do not change max_action_dim, max_state_dim, max_views
max_action_dim: 24
max_state_dim: 24
max_views: 3

data_groups:
  metaworld_sawyer:
    Evo1_MetaWorld:
      path: /content/Evo1_training_dataset/MetaWorld
      view_map:
        image_1: observation.images.image